name: '[CI] Library'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11.x
          distribution: zulu

      - uses: sbt/setup-sbt@v1

      - name: Compile project
        run: |
          sbt compile
          sbt run

      - name: Check scalafmt
        run: sbt scalafmtCheck

      - name: Run tests
        run: sbt test